# CQ-051: Does 'rooftop solar' resolve to the solar PV concept?
# Expected: non_empty
# Use case: UC-011

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sevocab: <https://skygest.dev/vocab/energy/>

SELECT ?concept WHERE {
  ?concept skos:altLabel "rooftop solar"@en ;
           skos:inScheme sevocab:TechnologyOrFuelScheme .
}
