PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pao: <https://purl.org/pao/>

# CQ-069: What messages were exchanged on a given communication channel?
# Expected: non-empty result set
SELECT ?message ?channel WHERE {
  ?message a pao:Message ;
           pao:sentViaChannel ?channel .
  ?channel a pao:CommunicationChannel .
}
