PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pao: <https://purl.org/pao/>

# CQ-080: What capabilities does a given external service expose?
# Expected: non-empty result set
SELECT ?service ?capability ?label ?type WHERE {
  ?service a pao:ExternalService ;
           pao:exposesCapability ?capability .
  ?capability rdfs:label ?label ;
              rdf:type ?type .
  FILTER(?type != pao:ServiceCapability)
}
