PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pao: <https://purl.org/pao/>

# CQ-067: What type of communication channel is a given channel?
# Expected: non-empty result set
SELECT ?channel ?channelType WHERE {
  ?channel a pao:CommunicationChannel ;
           pao:hasChannelType ?channelType .
  ?channelType a pao:ChannelType .
}
