PREFIX pao: <https://purl.org/pao/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# CQ-054: When was a memory item last accessed?
# Expected: non-empty result set
SELECT ?item ?lastAccess WHERE {
  ?item a pao:MemoryItem ;
        pao:hasLastAccessTime ?lastAccess .
}
