# CQ-116: What action does a schedule specify?
# Expected: non-empty result set (SELECT)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX pao: <https://purl.org/pao/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?schedule ?action_spec ?label WHERE {
  ?schedule a pao:Schedule ;
            pao:schedulesAction ?action_spec .
  ?action_spec rdfs:label ?label .
}
