PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pao: <https://purl.org/pao/>

# CQ-108: What failure type caused a given error recovery event?
# Expected: non_empty
SELECT ?recovery ?failureType ?label WHERE {
  ?recovery a pao:ErrorRecoveryEvent ;
            pao:hasFailureType ?failureType .
  ?failureType a pao:FailureType ;
               rdfs:label ?label .
}
