PREFIX enews: <http://example.org/ontology/energy-news#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# TBox-008: GridZone is subClassOf GeographicEntity
ASK {
  enews:GridZone a owl:Class ;
                  rdfs:subClassOf enews:GeographicEntity .
}
